#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-forwarder-config
  namespace: cf-system
data:
  fluentd.conf: |
    # Inputs
    <source>
      @type dummy
      tag forwarded
      dummy {
        "log": "This is log. Look on and dispair.",
        "app_id":"12345",
        "instance_id":"67890"
      }
    </source>

    <match **>
      @type forward
      <server>
        name fluent_dest
        host fluentd-ingress
        port 24224
      </server>
    </match>
