---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-dind

inputs:
  - name: cf-k8s-logging-main
  - name: cf-k8s-logging-ci

outputs:
  - name: kbld-lock-files

params:
  COMPONENT: ~
  DOCKERHUB_USERNAME: ((dockerhub.username))
  DOCKERHUB_PASSWORD: ((dockerhub.password))

run:
  path: cf-k8s-logging-ci/ci/tasks/build-images/task.sh
